unit uUpdate;

interface

uses
  FireDAC.Comp.Client, uLibFuncoesUpdate;

type
  TUpdate = class
  private
    class procedure P_Update001(pUpdate: TDatabaseUpdate);
  public
    class procedure Executar(pConnection: TFDConnection);
  end;

implementation

class procedure TUpdate.P_Update001(pUpdate: TDatabaseUpdate);
begin
  if not pUpdate.F_TabelaExiste('CLIENTE') then
  begin
    pUpdate.Connection.ExecSQL(
      'CREATE TABLE CLIENTE (' +
      'ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, ' +
      'NOME VARCHAR(100), ' +
      'CPF VARCHAR(14), ' +
      'EMAIL VARCHAR(150), ' +
      'TELEFONE VARCHAR(20), ' +
      'CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)' +
      ');'
    );
  end;
  if pUpdate.F_TabelaExiste('CLIENTE') then
  begin
    if not pUpdate.F_CampoExiste('CLIENTE','DATA_CADASTRO') then
      pUpdate.Connection.ExecSQL('ALTER TABLE CLIENTE ADD DATA_CADASTRO TIMESTAMP;');

    if not pUpdate.F_CampoExiste('CLIENTE', 'ATIVO') then
      pUpdate.Connection.ExecSQL('ALTER TABLE CLIENTE ADD ATIVO SMALLINT;');

    if not pUpdate.F_CampoExiste('CLIENTE','OBSERVACAO') then
      pUpdate.Connection.ExecSQL('ALTER TABLE CLIENTE ADD OBSERVACAO VARCHAR(500);');
  end;
  if not pUpdate.F_TabelaExiste('PRODUTO') then
  begin
    pUpdate.Connection.ExecSQL(
      'CREATE TABLE PRODUTO (' +
      'ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,' +
      'NOME VARCHAR(150) NOT NULL,' +
      'TIPO CHAR(1) NOT NULL,' +
      'PRECO DECIMAL(15,2) DEFAULT 0 NOT NULL,' +
      'ATIVO CHAR(1) DEFAULT ''S'' NOT NULL,' +
      'DESCRICAO VARCHAR(500),' +
      'CONSTRAINT PK_PRODUTO PRIMARY KEY (ID),' +
      'CONSTRAINT CK_PRODUTO_TIPO CHECK (TIPO IN (''P'', ''S'')),' +
      'CONSTRAINT CK_PRODUTO_ATIVO CHECK (ATIVO IN (''S'', ''N''))' +
    ');'
    );
  end;
  if not pUpdate.F_TabelaExiste('VENDA') then
  begin
    pUpdate.Connection.ExecSQL(
      'CREATE TABLE VENDA (' +
      'ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,' +
      'CLIENTE_ID INTEGER NOT NULL,' +
      'DATA_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,' +
      'VALOR_TOTAL DECIMAL(15,2) DEFAULT 0 NOT NULL,' +
      'STATUS CHAR(1) DEFAULT ''A'' NOT NULL,' +
      'CONSTRAINT PK_VENDA PRIMARY KEY (ID),' +
      'CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID)' +
      ');'
    );
  end;
  if not pUpdate.F_TabelaExiste('VENDA_ITEM') then
  begin
    pUpdate.Connection.ExecSQL(
      'CREATE TABLE VENDA_ITEM (' +
      'ID INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,' +
      'VENDA_ID INTEGER NOT NULL,' +
      'PRODUTO_ID INTEGER NOT NULL,' +
      'QUANTIDADE DECIMAL(15,3) DEFAULT 1 NOT NULL,' +
      'VALOR_UNITARIO DECIMAL(15,2) NOT NULL, ' +
      'DESCONTO DECIMAL(15,2) DEFAULT 0 NOT NULL,' +
      'VALOR_TOTAL DECIMAL(15,2) NOT NULL,' +
      'CONSTRAINT PK_ITEM_VENDA PRIMARY KEY (ID),' +
      'CONSTRAINT FK_ITEM_VENDA_VENDA FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID),' +
      'CONSTRAINT FK_ITEM_VENDA_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID)' +
      ');'
    );
  end;
end;

class procedure TUpdate.Executar(pConnection: TFDConnection);
var
  vUpdate: TDatabaseUpdate;
begin
  vUpdate := TDatabaseUpdate.Create(pConnection);
  try
    P_Update001(vUpdate);
  finally
    vUpdate.Free;
  end;
end;

end.
